server:
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: "prod"

logging:
  config: "classpath:logback-dev.xml"

app:
  cors:
    enable: true
    allow-credentials: true
    exposed-headers:
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-headers:
      - content-type
      - authorization
      - x-com-persist
      - X-Auth-Token
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-methods:
      - GET
    allowed-origins:
      -
  cache-lifetime-in-seconds: 86400
  use-gar: false
  gar:
    ressources-diffusables-uri: 'ressources/diffusables/uri'
    download-location-path: '/path/to/containing/folder'
    download-file-name: 'name-of-file.json'
  no-gar:
    local-json-file-path: '/local/ressourcesDiffusables.json'
  soffit:
    jwt-signature-key: 'signatureKey'