spring:
  config:
    activate:
      on-profile: 'default-config'

---

server:
  port: 8090
  servlet:
    context-path: /spring-api
  error:
    whitelabel.enabled: true
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

logging:
  config: "classpath:logback.xml"

spring:
  profiles:
    active: @spring.profiles.active@
    group:
      dev: dev
      test: test
      prod: prod
      ci: test

  cache.jcache.config: classpath:ehcache.xml

app:
  cors:
    enable: true
    allow-credentials: true
    exposed-headers:
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-headers:
      - content-type
      - authorization
      - x-com-persist
      - X-Auth-Token
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-methods:
      - GET