server:
  port: 8090
  servlet:
    context-path: /spring-api
  error:
    whitelabel.enabled: true
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

#logging:
#  level:
#    web: DEBUG
#    fr: DEBUG

spring:
  config:
    import:
      - classpath:private.yml
      - classpath:cors.yml
  cache:
    jcache:
      config: classpath:ehcache.xml
